### ISSUE TITLE
AI戦闘システム、どう？

### ISSUE THREAD

**Issue by yoshinotaichi** [yoshinotaichi/dev_ex#20]
テーマとして、AIによる認識＋攻撃システムを実装するのは楽しそう！

**Comment by RikiishiSuzunosuke** [comment]
ハードウェアを扱うのは難しそうですが、楽しそうですね

**Comment by superTonguman** [comment]
押し出し式の水鉄砲がよさそうですね

**Comment by Zansan-bit** [comment]
急に攻撃したら反感を買う可能性があるので見かけで何をするのか分かる。
叩いて被ってじゃんけんポン等がいいと思います。

**Comment by YIFAN-888** [comment]
_楽しそうです_

**Comment by Ishimoto0314** [comment]
面白そうですね

**Comment by RikiishiSuzunosuke** [comment]
> 押し出し式の水鉄砲がよさそうですね

リプライもできますね

**Comment by Zansan-bit** [comment]
> 急に攻撃したら反感を買う可能性があるので見かけで何をするのか分かる。
> 叩いて被ってじゃんけんポン等がいいと思います。

**Comment by yoshitake266** [comment]
安全面を配慮するなら、ARでやるのも大変そうですが楽しそうですね
